server:
  port: 8083
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://192.168.1.220:3306/qycl_qd2_0708?characterEncoding=UTF-8&autoReconnect=true #换成自己的数据库地址
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: karakal

logging:
  level:
    com.linchen.face: info
   #调试使用  是否打印sql语句 mapper路径 参数设置debug
  file:
    path: /data/qd/qycl-face/logs/

mvc:
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp
